### ISSUE TITLE
Out of date?

### ISSUE THREAD

**Issue by mixxit** [DyonR/docker-Jackettvpn#13]
```
 Your version of Jackett v0.11.534.0 is very old. Multiple indexers are likely to fail when using an old version. Update to the latest version of Jackett.
```

**Comment by DyonR** [comment]
If you build the Docker like half a year ago and never update it, yes it is out of date.
When you build this Docker it grabs the latest Jackett release, so if you did never rebuild it, you're still on the version that it was on when you build it.

My Docker repo checks every hour if Jackett released a new stable version, if so, it rebuilds the Docker image. See https://hub.docker.com/r/dyonr/jackettvpn/builds
I recommend to use my Docker image, unless you made some changes yourself.

**Comment by mixxit** [comment]
I do

Sent from ProtonMail mobile

-------- Original Message --------
