### ISSUE TITLE
Error WebApp behind container

### ISSUE THREAD

**Issue by Technikte** [DyonR/docker-Jackettvpn#20]
Hello,
i did succesfully setup this container and with curl and ping I can verify internet acceses and the vpn tunnel. Then I follwed this video https://www.youtube.com/watch?v=znSu_FuKFW0 and setup an other container (will name it Docker 2.) behind this network. On 2. I can still verify the internet acceses and also that I am using the vpn tunnel. Even from my pc and the 2. container I can ping each other.

I did the addional port mapping in the parent container (jacketvpn) for my 2. container but I can't still accses the web server on that. 
My guess would be that the iptable rules block this but I am not quite sure maybe its the fault of something in 2. container. Feel free to close this issue then.

To clarify the 2. container should use the vpn tunnel for any internet usage and everything local should bypass the tunnel. I have set "LAN_NETWORK" correct and I can reach the jacket webui.

`2. Container (:6596) <---> Jackettvpn <---> My PC`

**Comment by DyonR** [comment]
This is indeed caused by iptables.
My iptables.sh was never updated to support container linking like this.
I'll push another update soon that copies how Binhex' containers do it. Note that you also would need to device the additional ports in yet another new environment variable.

**Comment by DyonR** [comment]
A new updates has been pushed.
Add a new environment variable called 'ADDITIONAL_PORTS' and add 6596 to it.
Also don't forget to add a port mapping.

**Comment by Technikte** [comment]
I have added the port and the mapping in the jackett container but got still problems.
A part of the log from jackett.
```
--------------------
iptable_mangle 16384 7
ip_tables 24576 15 iptable_filter,iptable_nat,iptable_mangle
2020-06-14 20:15:34.681344 [info] iptable_mangle support detected, adding fwmark for tables
[info] Adding additional incoming port 6596 for eth0
[info] Adding additional outgoing port 6596 for eth0
2020-06-14 20:15:34.723554 [info] iptables defined as follows...
--------------------
-P INPUT DROP
-P FORWARD ACCEPT
-P OUTPUT DROP
-A INPUT -i tun0 -j ACCEPT
-A INPUT -s 172.17.0.0/16 -d 172.17.0.0/16 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --sport 44 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 9117 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --sport 9117 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 6596 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --sport 6596 -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A OUTPUT -o tun0 -j ACCEPT
-A OUTPUT -s 172.17.0.0/16 -d 172.17.0.0/16 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --dport 44 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --dport 9117 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --sport 9117 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --dport 6596 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --sport 6596 -j ACCEPT
-A OUTPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
--------------------
```

Inside the console from jakket container.. just seems to work without any problem.
```
curl 127.0.0.1:6595 > test.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 66317  100 66317    0     0  63.2M      0 --:--:-- --:--:-- --:--:-- 63.2M
```

Just a cmd on my windows main machine which is the same lan.. its justs times out (in Firefox the same)
```
curl 192.168.xxx.200:6595
curl: (7) Failed to connect to 192.168.1.200 port 6595: Timed out
```

I  have the port 6595 mapped in the jackett container and in the other app container.
Any idea whats wrong or how to solve this ?

**Comment by Technikte** [comment]
I may be very sorry, now I noticed a shifted the port mapping in jackett container by 1. It was not 6595..
I will try to check all ports and if it works, then reply here again.

**Comment by DyonR** [comment]
No problem of course! Can happen of course 😉 
If you do not forget to restart 'container 2.' after adding re-applying setting to JackettVPN.  
I also had the issue in which I thought it didn't work, but all it took was to restart the 2nd container.

**Comment by Technikte** [comment]
Now I getting a other error which I worked around all the time. If update the jackett container or somehting like this it cant connect to the vpn server. It says its connected but I cant even ping google from the jackett container. The last times only the change of the vpn server helped.

```

Sun Jun 14 20:58:13 2020 us=20465 Initialization Sequence Completed
Sun Jun 14 20:59:10 2020 us=488381 [Server_hamburg.xxxxxxxxxxxxx.com] Inactivity timeout (--ping-restart), restarting
Sun Jun 14 20:59:10 2020 us=488522 TCP/UDP: Closing socket
Sun Jun 14 20:59:10 2020 us=488544 SIGUSR1[soft,ping-restart] received, process restarting
Sun Jun 14 20:59:10 2020 us=488559 Restart pause, 5 second(s)

PING 8.8.8.8
```

**Comment by Technikte** [comment]
With the correct port mapping it now works. The vpn connection issue is pretty strange to me, maybe my firewall hold the states to long some weird like this. If happens again often, will do a new issue then.
closed/fixed. Thanks! 👍
