### ISSUE TITLE
Out of date again

### ISSUE THREAD

**Issue by mixxit** [DyonR/docker-Jackettvpn#31]
``` Your version of Jackett v0.14.433.0 is very old. Multiple indexers are likely to fail when using an old version. Update to the latest version of Jackett.```

I am using your docker image dyonr/jackettvpn

is something wrong again?

**Comment by DyonR** [comment]
My image on Docker Hub updates within an hour [normally] after Jackett releases a new version.
Docker images do not update automatically, this is normal behaviour. So you have to do it manually.  
  
To update the docker, you need to remove the old image and pull the new one.  
I think this blog post explains well how to do it: https://ma.ttias.be/update-docker-container-latest-version/  
You could also Google how to update containers for your specific system.
