### ISSUE TITLE
Container reboot on itself

### ISSUE THREAD

**Issue by Dudu514** [DyonR/docker-Jackettvpn#35]
Hi, i installed the docker image but from some ressons it stall at: 

2020-12-03 23:26:31.570989 [ERROR] LAN_NETWORK not defined (via -e LAN_NETWORK), exiting...

My docker run (for the network part) is like that:

...
-e "LOCAL_NETWORK=10.0.0.0/24,10.6.0.0/24" \
...

I tried to review this line but everything seems fine.

**Comment by DyonR** [comment]
You're using LOCAL_NETWORK and not LAN_NETWORK 😉

**Comment by Dudu514** [comment]
Hahah. I felt that i did something dumb and there it is... I can't read anymore haven't had a good sleep in while hahah. Thanks sorry for that.

**Comment by DyonR** [comment]
No problem! Sometimes you just need someone else to look at an error
