### ISSUE TITLE
JacketVPN + FlareSolverr

### ISSUE THREAD

**Issue by Zazou89** [DyonR/docker-Jackettvpn#42]
Hello,

I'm desperately trying to add [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr) to JacketVPN. I tunneled FlareSolverr to JacketVPN but I can't access to the FlareSolverr UI.

I use unraid and both docker version of JackettVPN and FlareSolverr.

![image](https://user-images.githubusercontent.com/206181/104126768-b4c87780-535e-11eb-8263-f24e4875010d.png)

Do you know a procedure which works ?
Thank you !

**Comment by DyonR** [comment]
I will see if I can reproduce this and see what might be wrong

**Comment by DyonR** [comment]
Using the Docker Image I posted above, it works for me.  
Did you **add another **port** to jackettvpn?

- Edit jackettvpn
- Scroll down
- Click  Add another Path, Port, Variable, Label or Device
- Config type: Port  
- **Name: FlareSolverr**  
- **Container Port: 8191**  
- **Host Port: 8191** (Or any other port number you want to access FlareSolverr from externally)  
- **Default Value: 8191**  
- **Connection Type:  TCP**
- (Additionally, **Description: Port used for FlareSolverr**)
  
  
![image](https://user-images.githubusercontent.com/16341409/104143466-d4dc5300-53bf-11eb-83e5-0e3b031bc0f9.png)

**Comment by Zazou89** [comment]
Thanks for your answer ! 

Yes I use FlareSolverr from docker hub (flaresolverr/flaresolverr).

And yes I added additional port on JackettVPN. I have a timeout when I want to access to FlareSolverr API (IP:8191). 

I’m not at my home, I’ll double check settings.

**Comment by DyonR** [comment]
Alright! Let me know 😄  
Actually, it might be something else!
This are the 4 things I did to get it working:  

- Add flaresolverr/flaresolverr with --net-container="jackettvpn" (also visible on your screenshot, don't think that's it)  
- Add a new port called flaresolverr with 8191 as values (also visible on your screenshot, don't think that's it)  
**- Edit jackettvpn, _show more settings_, add 8191 to ADDITIONAL_PORTS** (can't confirm that on your screenshot, that might be it!)  
- Add a new port called flaresolverr with 8191 as values, done (actually, that is visible on your screenshot)

**Comment by Zazou89** [comment]
Hey,

Sorry for the delay, I forgot to add port to ADDITIONAL_PORTS. Unfortunately, I still have a timeout :( 
I checked logs but I don't understand why isn't working : 

![image](https://user-images.githubusercontent.com/206181/104178553-d4b57500-540a-11eb-8c68-185db526ce6c.png)
![image](https://user-images.githubusercontent.com/206181/104178589-e4cd5480-540a-11eb-8a4d-c7a5dd645ea9.png)

When I check : http://192.168.1.9:8191, I have a timeout after 20-30 s.

Can it be a problem with my VPN ? I use Windscribe, but no error when I check an indexer without FlareSolverr. So I think not.

**Comment by Zazou89** [comment]
Well I can't access JackettVPN UI anymore (timeout), that's odd.

**Comment by DyonR** [comment]
I also use Windscribe, so I don't think that will be the problem.  
However, I did test it with wireguard instead of openvpn (why are you using openvpn when Windscribe provides wireguard config files?)  
I don't see anything wrong with your Jackettvpn settings, but does your FlareSolverr have a 8191 port mapping?

**Comment by Zazou89** [comment]
Because I read experimental for Wireguard in JacketVPN :o 
I'll try to switch to wireguard.

I need to put a port on FlareSolverr container ?

**Comment by Zazou89** [comment]
Port 443 on Windscribe ?

**Comment by DyonR** [comment]
> I also use Windscribe, so I don't think that will be the problem.
> However, I did test it with wireguard instead of openvpn (why are you using openvpn when Windscribe provides wireguard config files?)
> I don't see anything wrong with your Jackettvpn settings, but does your FlareSolverr have a 8191 port mapping?

Wait, my bad, I don't think that is the procedure indeed. I just woke up, my bad 😓

**Comment by Zazou89** [comment]
Switched to Wireguard (that's easier !), but no change. FlareSolverr doesn't tell me lot of thing : 

```
> flaresolverr@1.2.3 start
> node ./dist/index.js

2021-01-11T12:02:25.655Z INFO REQ-0 FlareSolverr v1.2.3 listening on http://0.0.0.0:8191
```

**Comment by DyonR** [comment]
> Lol no problem 😄
> 
> Switched to Wireguard (that's easier !), but no change. FlareSolverr doesn't tell me lot of thing :
> 
> ```
> > flaresolverr@1.2.3 start
> > node ./dist/index.js
> 
> 2021-01-11T12:02:25.655Z INFO REQ-0 FlareSolverr v1.2.3 listening on http://0.0.0.0:8191
> ```

FlareSolverr shows me the exact same output if I check the logs. Are you still unable to connect to http://192.168.1.9:8191/  
  
This is what my logs show after connecting to the IP+port;
```
> flaresolverr@1.2.3 start
> node ./dist/index.js

2021-01-11T12:10:35.655Z INFO REQ-0 FlareSolverr v1.2.3 listening on http://0.0.0.0:8191
2021-01-11T12:10:45.459Z INFO REQ-1 Incoming request: GET /
2021-01-11T12:10:45.459Z INFO REQ-1 Successful response in 0 s
2021-01-11T12:10:45.459Z INFO REQ-1 FlareSolverr is ready!
2021-01-11T12:10:45.569Z INFO REQ-2 Incoming request: GET /favicon.ico
2021-01-11T12:10:45.570Z ERROR REQ-2 Body must be in JSON format
```

**Comment by DyonR** [comment]
Can you also send the log of your jackettvpn?  
There should be no private info in there, but be sure to quickly check it before sharing it.

**Comment by Zazou89** [comment]
> 
> 
> > Lol no problem 😄
> > Switched to Wireguard (that's easier !), but no change. FlareSolverr doesn't tell me lot of thing :
> > ```
> > > flaresolverr@1.2.3 start
> > > node ./dist/index.js
> > 
> > 2021-01-11T12:02:25.655Z INFO REQ-0 FlareSolverr v1.2.3 listening on http://0.0.0.0:8191
> > ```
> 
> FlareSolverr shows me the exact same output if I check the logs. Are you still unable to connect to http://192.168.1.9:8191/
> 
Yes unable to connect, to this IP:PORT

> This is what my logs show after connecting to the IP+port;
> 
> ```
> > flaresolverr@1.2.3 start
> > node ./dist/index.js
> 
> 2021-01-11T12:10:35.655Z INFO REQ-0 FlareSolverr v1.2.3 listening on http://0.0.0.0:8191
> 2021-01-11T12:10:45.459Z INFO REQ-1 Incoming request: GET /
> 2021-01-11T12:10:45.459Z INFO REQ-1 Successful response in 0 s
> 2021-01-11T12:10:45.459Z INFO REQ-1 FlareSolverr is ready!
> 2021-01-11T12:10:45.569Z INFO REQ-2 Incoming request: GET /favicon.ico
> 2021-01-11T12:10:45.570Z ERROR REQ-2 Body must be in JSON format
> ```
Nothing added on logs when I'm trying to connect to IP;PORT

**Comment by Zazou89** [comment]
> 
> 
> Can you also send the log of your jackettvpn?
> There should be no private info in there, but be sure to quickly check it before sharing it.
Sure : https://privatebin.net/?dc8d53a72f1bc6f8#FenFa3yxN4L8ppocVmwt9iqaV7E7e6fubnLoSUGQnyFE

**Comment by DyonR** [comment]
Isn't your LAN Network supposed to be 192.168.1.0/24 instead of
192.168.0.0/24?

Op ma 11 jan. 2021 13:20 schreef Zazou89 <notifications@github.com>:

**Comment by Zazou89** [comment]
Thank you !!! That's that !

```
2021-01-11T12:32:31.304Z INFO REQ-0 FlareSolverr v1.2.3 listening on http://0.0.0.0:8191
2021-01-11T12:32:37.325Z INFO REQ-1 Incoming request: GET /
2021-01-11T12:32:37.325Z INFO REQ-1 Successful response in 0 s
2021-01-11T12:32:37.325Z INFO REQ-1 FlareSolverr is ready!
```

**Comment by DyonR** [comment]
Nice! It are always the small things you get stuck on 😝 Enjoy the container, if you have any issues, feel free to open up a new issue 😄
