### ISSUE TITLE
VPN disconnecting randomly

### ISSUE THREAD

**Issue by evakq8r** [DyonR/docker-Jackettvpn#9]
Hi,

Have been using JackettVPN for a while (via Docker on a Synology NAS) but have noticed that the VPN session will drop completely but it will not restart the container after doing so. End result is that the trackers I have listed will fail to connect (as the ISP has chosen it to be a good idea and drop all routing to said trackers... hence the need for the VPN).

Specs:

VPN Provider: *PIA* (doesn't matter which connection I go through, the same behaviour is experienced across them all)
NAS: *Synology DS918+ running latest DSM: DSM 6.2.1-23824 Update 4*

Previously this was producing this behaviour every few hours, until I added the following environment variable to the docker image (found from a TransmissionVPN issue (can't remember link, sorry)):

> -e VPN_OPTIONS=--inactive 3600 --ping 10 --ping-exit 60 \

This allowed the JackettVPN connection to remain working for exactly 1 week and 2 hours, before it timed out again and failed. The container itself does not notice the VPN connection has disappeared, and the only way to fix is to restart the container to re-establish VPN connection.

Example: - successful VPN connection 10/02:

*2019-02-10 12:50:26 | stdout | 2019-02-10 12:50:26.632286 [info] Starting Jackett daemon...
2019-02-10 12:50:26 | stdout | Logging to /config/Jackett/log.txt.
2019-02-10 12:50:27 | stdout | 2019-02-10 12:50:27.697847 [info] Jackett PID: 192
2019-02-10 12:50:27 | stdout | 2019-02-10 12:50:27.722848 [info] Started Jackett daemon successfully...*

Connection failure 1 week and 2 hours later:

*Sun Feb 17 14:50:16 2019 [a08ba64d38b4ad4426d08e0c41bb9bad] Inactivity timeout (--ping-restart), restarting
2019-02-17 14:50:16 | stdout | 
2019-02-17 14:50:16 | stdout | Sun Feb 17 14:50:16 2019 SIGUSR1[soft,ping-restart] received, process restarting
Sun Feb 17 14:50:21 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]<VPN endpoint>:1197
2019-02-17 14:50:21 | stdout | 
2019-02-17 14:50:21 | stdout | Sun Feb 17 14:50:21 2019 UDP link local: (not bound)
2019-02-17 14:50:21 | stdout | Sun Feb 17 14:50:21 2019 UDP link remote: [AF_INET]<VPN endpoint>:1197
Sun Feb 17 14:50:22 2019 [a08ba64d38b4ad4426d08e0c41bb9bad] Peer Connection Initiated with [AF_INET]<VPN endpoint>:1197
2019-02-17 14:50:22 | stdout | 
**2019-02-17 14:50:24 | stdout | Sun Feb 17 14:50:24 2019 AUTH: Received control message: AUTH_FAILED**
Sun Feb 17 14:50:24 2019 /sbin/ip addr del dev tun0 local 10.42.10.6 peer 10.42.10.5
2019-02-17 14:50:24 | stdout | 
-- | -- | --
2019-02-17 14:50:24 | stdout | Sun Feb 17 14:50:24 2019 SIGTERM[soft,auth-failure] received, process exiting*

I'm not sure what's causing it and I'm also not sure whether it's something simple to fix, but any help here would be appreciated. Thanks

**Comment by Dinth** [comment]
Im seeing same thing.
```
Tue Oct 15 20:15:35 2019 [6acb1a23e1777dd84ba3e0c77bdab1a0] Inactivity timeout (--ping-restart), restarting
Tue Oct 15 20:15:35 2019 SIGUSR1[soft,ping-restart] received, process restarting
Tue Oct 15 20:15:40 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]188.240.220.26:1198
Tue Oct 15 20:15:40 2019 UDP link local: (not bound)
Tue Oct 15 20:15:40 2019 UDP link remote: [AF_INET]188.240.220.26:1198
Tue Oct 15 20:16:40 2019 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Tue Oct 15 20:16:40 2019 TLS Error: TLS handshake failed
Tue Oct 15 20:16:40 2019 SIGUSR1[soft,tls-error] received, process restarting
Tue Oct 15 20:16:45 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]188.240.220.26:1198
Tue Oct 15 20:16:45 2019 UDP link local: (not bound)
Tue Oct 15 20:16:45 2019 UDP link remote: [AF_INET]188.240.220.26:1198
Tue Oct 15 20:17:45 2019 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Tue Oct 15 20:17:45 2019 TLS Error: TLS handshake failed
Tue Oct 15 20:17:45 2019 SIGUSR1[soft,tls-error] received, process restarting
```

It's a weird one. Ive got another, similar docker container - qbittorrentvpn and it has exactly same problem https://github.com/MarkusMcNugen/docker-qBittorrentvpn/issues/32.
This being said, jackettvpn was working fine for weeks and only yesterday, after i restarted qbittorrentvpn numerous times (because of this error), jackettvpn also started disconnecting. This may indicate that the problem is with PIA or the OVPN file im using, as restarting one docker container should not cause misbehaviour of another one.

**Comment by Dinth** [comment]
After looking into it further i found out that the logs are timestamped one hour behind and im assuming that the container does not accept -e TZ parameter. Maybe that's what is causing problems with TLS handshake?

**Comment by DyonR** [comment]
I've added `tzdata` to the installation of the Docker, which means the date/time should be correct now.
Please update your jackettvpn docker and check if the data/time for the log-files and system are correct.  
Please let me know if this also fixes the VPN issue that you are having.  
I personally never had this issue, so it is hard for me to troubleshoot this, but I'll do my best with the information that I receive.

**Comment by Dinth** [comment]
Thanks @DyonR, the logs are now timestamped correctly, although i still cannot estabilish VPN connection. I will keep looking into that.

**Comment by evakq8r** [comment]
Thanks @DyonR; I've updated to the latest pull and logs are timestamped correctly, though time wasn't the issue for me as the logs looked to be pulling the correct time previously.

I've removed the -e VPN_OPTIONS=--inactive 3600 --ping 10 --ping-exit 60 \ options for the moment to see whether the behaviour returns with the new image.

**Comment by Dinth** [comment]
@DyonR so far so good, it seems that tzdata fixed the problem with connecting using 128bit certificate from PIA. 
256 bit PIA certs are still failing though.

**Comment by DyonR** [comment]
Pull request #17 fixed this issue by restarting the container automatically.  
Please note that you must run the container with docker run --restart unless-stopped
